### ISSUE TITLE
間隙が小さくなりすぎると遅延が起こりそう

### ISSUE THREAD

**Issue by nebocco** [dem08656775/newincrementalgame#31]
例えば間隙が100msを下回った場合、更新は100msごとに行う代わりに各増加量を 100/間隙 倍する、などすれば遅延は防げそう
ただ更新式が不正確になるので悩ましいところではある

**Comment by dem08656775** [comment]
Derivative clicker はそんな感じですね (100~1000msに収まるように、同時に10べき回分更新）
誤差みたいなもんだから大丈夫だと思います

**Comment by dem08656775** [comment]
軽く準備だけしました

**Comment by nebocco** [comment]
長らく放置していましたが #45 で解決しそうなので閉じます
